trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
  BuildShared: false
  BuildConsole: false

stages:
- stage: Build
  jobs:
  - job: 'Determine_Changes'
    displayName: 'Determine jobs to run'
    steps: 
    - powershell: |
        $changedFiles = $(git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion))
        $sharedMatches = Select-String -InputObject $changedFiles -Pattern "PipelineTrigger.Shared/" -AllMatches
        $consoleMatches = Select-String -InputObject $changedFiles -Pattern "PipelineTrigger.Console/" -AllMatches

        $buildShared = $sharedMatches.Matches.Count -gt 0
        $buildConsole = $consoleMatches.Matches.Count -gt 0

        Write-Host "##vso[task.setvariable variable=BuildShared]$buildShared"
        Write-Host "##vso[task.setvariable variable=BuildConsole]$buildConsole"
      name: files_changed

  - job: 'Output_Builds'
    displayName: 'Output builds that will run'
    dependsOn: 'Determine_Changes'
    steps: 
    - script: echo 'BuildShared ${{ variables.BuildShared }}''
    - script: echo 'BuildConsole ${{ variables.BuildConsole }}''

  - template: pipeline/build.yml
    parameters:
      appName: 'PipelineTriggerConsole'
      projectPath: 'src/PipelineTrigger/PipelineTrigger.Console'

  - template: pipeline/build.yml
    parameters:
      appName: 'PipelineTriggerShared'
      projectPath: 'src/PipelineTrigger/PipelineTrigger.Shared'
