trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build Console
  jobs:
  - template: pipeline/build.yml
    parameters:
      appName: PipelineTrigger.Console
      projectPath: 'src/PipelineTrigger/PipelineTrigger.Console'

- stage: Build Shared
  jobs:
  - template: pipeline/build.yml
    parameters:
      appName: PipelineTrigger.Shared
      projectPath: 'src/PipelineTrigger/PipelineTrigger.Shared'
