trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: 'Determine_Changes'
    displayName: 'Determine jobs to run'
    steps: 
    - checkout: self
      fetchDepth: 0

    - powershell: |
        $changedFiles = $(git diff --name-only HEAD^ HEAD);
        $temp=$changedFiles -split ' '; 
        $count=$temp.Length;

        echo $changedFiles
        echo $count

        $sharedMatches = Select-String -InputObject $changedFiles -Pattern "PipelineTrigger.Shared" -AllMatches
        $consoleMatches = Select-String -InputObject $changedFiles -Pattern "PipelineTrigger.Console" -AllMatches

        $buildShared = $sharedMatches.Matches.Count -gt 0
        $buildConsole = $consoleMatches.Matches.Count -gt 0

        echo $sharedMatches.Matches.Count
        echo $consoleMatches.Matches.Count

        echo $buildShared
        echo $buildConsole

        Write-Host "##vso[task.setvariable variable=outBuildConsole;isoutput=true]true"
        Write-Host "##vso[task.setvariable variable=outBuildShared;isoutput=true]$buildShared"
      name: files_changed

  - job: 'Output_Builds'
    displayName: 'Output builds that will run'
    dependsOn: 'Determine_Changes'
    variables:
      BuildShared: $[ dependencies.Determine_Changes.outputs['files_changed.outBuildShared'] ]
      BuildConsole: $[ dependencies.Determine_Changes.outputs['files_changed.outBuildConsole'] ]
    steps: 
    - script: echo $(BuildShared)
    - script: echo $(BuildConsole)

  - job: 'Run_For_Shared'
    displayName: 'Shared changed'
    dependsOn: 'Determine_Changes'
    variables:
      runJob: $[ dependencies.Determine_Changes.outputs['files_changed.outBuildShared'] ]
    condition: eq(variables.runJob, true)
    steps:
    - script: echo 'Shared has changed'

  - job: 'Run_For_Console'
    displayName: 'Console changed'
    dependsOn: 'Determine_Changes'
    variables:
      runJob: $[ dependencies.Determine_Changes.outputs['files_changed.outBuildConsole'] ]
    condition: eq(variables.runJob, true)
    steps:
    - script: echo 'Console has changed'

  # - template: pipeline/build.yml
  #   parameters:
  #     appName: 'PipelineTriggerConsole'
  #     projectPath: 'src/PipelineTrigger/PipelineTrigger.Console'

  # - template: pipeline/build.yml
  #   parameters:
  #     appName: 'PipelineTriggerShared'
  #     projectPath: 'src/PipelineTrigger/PipelineTrigger.Shared'
