trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - template: pipeline/build.yml
    parameters:
      appName: 'PipelineTriggerConsole'
      projectPath: 'src/PipelineTrigger/PipelineTrigger.Console'

  - template: pipeline/build.yml
    parameters:
      appName: 'PipelineTriggerShared'
      projectPath: 'src/PipelineTrigger/PipelineTrigger.Shared'
