trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: 'Determine_Changes'
    displayName: 'Determine jobs to run'
    variables:
      BuildShared: false
      BuildConsole: false
    steps: 
    - checkout: self
      fetchDepth: 0

    - powershell: |
        $changedFiles = $(git diff --name-only HEAD^ HEAD);
        $temp=$changedFiles -split ' '; 
        $count=$temp.Length;

        echo $changedFiles
        echo $count

        $sharedMatches = Select-String -InputObject $changedFiles -Pattern "PipelineTrigger.Shared" -AllMatches
        $consoleMatches = Select-String -InputObject $changedFiles -Pattern "PipelineTrigger.Console" -AllMatches

        $buildShared = $sharedMatches.Matches.Count -gt 0
        $buildConsole = $consoleMatches.Matches.Count -gt 0

        echo $sharedMatches.Matches.Count
        echo $consoleMatches.Matches.Count

        echo $buildShared
        echo $buildConsole

        Write-Host "##vso[task.setvariable variable=variables.BuildShared]$buildShared"
        Write-Host "##vso[task.setvariable variable=variables.BuildConsole]$buildConsole"
      name: files_changed

  - job: 'Output_Builds'
    displayName: 'Output builds that will run'
    dependsOn: 'Determine_Changes'
    variables:
      BuildShared: $[ dependencies.Determine_Changes.variables.BuildShared ]
      BuildConsole: $[ dependencies.Determine_Changes.variables.BuildConsole ]
    steps: 
    - script: echo 'BuildShared ${{ variables.BuildShared }}'
    - script: echo 'BuildConsole ${{ variables.BuildConsole }}'

  # - template: pipeline/build.yml
  #   parameters:
  #     appName: 'PipelineTriggerConsole'
  #     projectPath: 'src/PipelineTrigger/PipelineTrigger.Console'

  # - template: pipeline/build.yml
  #   parameters:
  #     appName: 'PipelineTriggerShared'
  #     projectPath: 'src/PipelineTrigger/PipelineTrigger.Shared'
