jobs:
  - job: 'Determine_Changes'
    displayName: 'Determine jobs to run'
    steps: 
    - checkout: self
      fetchDepth: 0
    - powershell: ./pipeline/Determine-Changes.ps1
      displayName: 'Check for changes in Communications.Shared'
      name: files_changed

  - job: 'Run_For_Shared'
    displayName: 'Shared changed'
    dependsOn: 'Determine_Changes'
    variables:
      runJob: $[ dependencies.Determine_Changes.outputs['files_changed.outBuildShared'] ]
    condition: eq(variables.runJob, true)
    steps:
    - task: Bash@3
      displayName: 'Output state'
      inputs:
        targetType: "inline"
        script: |
          echo 'Shared has changed'

    - task: UseDotNet@2
      displayName: 'Restore'
      inputs: 
        command: 'restore'
        projects: "src/PipelineTrigger/PipelineTrigger.Shared/PipelineTrigger.Shared.csproj"