jobs:
  - job: 'Determine_Changes'
    displayName: 'Determine jobs to run'
    steps: 
    - checkout: self
      fetchDepth: 0
    - powershell: ./pipeline/Determine-Changes.ps1
      name: files_changed

  - job: 'Run_For_Shared'
    displayName: 'Shared changed'
    dependsOn: 'Determine_Changes'
    variables:
      runJob: $[ dependencies.Determine_Changes.outputs['files_changed.outBuildShared'] ]
    condition: eq(variables.runJob, true)
    steps:
    - script: echo 'Shared has changed'

  - job: 'Run_For_Console'
    displayName: 'Console build'
    dependsOn: 'Determine_Changes'
    variables:
      runJob: $[ dependencies.Determine_Changes.outputs['files_changed.outBuildConsole'] ]
    condition: eq(variables.runJob, true)
    steps:
    - script: echo 'Console has changed'